# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/sphinx/source/conf.py

build:
  os: "ubuntu-22.04"
  commands:
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - wget https://github.com/sofa-framework/SofaPython3/releases/download/v24.12.00-doc-generation/SofaPython3_v24.12.00_docs.zip
    - unzip  SofaPython3_v24.12.00_docs.zip
    - cp --recursive build/html/* $READTHEDOCS_OUTPUT/html/
